### ISSUE TITLE
azure-metrics-exporter: The fix for namespaceSelector breaks the deployment

### ISSUE THREAD

**Issue by ThomasMinor** [webdevops/helm-charts#60]
The addition of a [namespaceSelector](https://github.com/webdevops/helm-charts/commit/32bcdf88964677006df1add417164112420f9e27) breaks the deployment in our environment throwing a nil pointer error:

` Error: template: azure-metrics-exporter/templates/prometheus/servicemonitor.metricprobe.yaml:23:16: executing "azure-metrics-exporter/templates/prometheus/servicemonitor.metricprobe.yaml" at <.Values.prometheus.monitor.namespaceSelector>: nil pointer evaluating interface {}.prometheus`

**Comment by ThomasMinor** [comment]
Is addressed by #62

**Comment by Moglum** [comment]
https://github.com/webdevops/helm-charts/pull/62 fixed only part of the problem. We're still getting:
 
`Error: template: azure-metrics-exporter/templates/_helpers.tpl:36:16: executing "azure-metrics-exporter.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride`

It's caused by passing the local context instead of `$root` here https://github.com/webdevops/helm-charts/blob/main/charts/azure-metrics-exporter/templates/prometheus/servicemonitor.metricprobe.yaml#L28

I'll open a PR to fix it shortly.

**Comment by NoamVH** [comment]
Hello, was this fixed? I am still having this problem.

**Comment by Moglum** [comment]
Fixed in https://github.com/webdevops/helm-charts/pull/86
